apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: button
  name: button
spec:
  replicas: 3
  selector:
    matchLabels:
      app: button
  template:
    metadata:
      labels:
        app: button
    spec:
      serviceAccountName: homelab-service-account
      containers:
      - name: button
        image: registry.tino.sh/homelab-button
        envFrom:
        - configMapRef:
            name: homelab-config
        volumeMounts:
          - mountPath: /sys
            name: sys
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      tolerations:
      - key: "node-role.kubernetes.io"
        value: "master"
        effect: "NoSchedule"
      nodeSelector:
        arch: arm64
        hostname: main-node01
