apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.tino.sh/homelab-button
    context: ../../
    docker:
      target: button
  - image: registry.tino.sh/homelab-www
    context: ../../
    docker:
      target: www
deploy:
  kustomize: {}
